### ISSUE TITLE
我看了下内容基本和 datawhale 组队课程一致，建议在readme添加上来源出处。

### ISSUE THREAD

**Issue by mba1398** [unclestrong/sql_teamlearning#1]
我看了下内容基本和 datawhale 组队课程一致，建议在readme添加上来源出处。

**Comment by unclestrong** [comment]
> 我看了下内容基本和 datawhale 组队课程一致，建议在readme添加上来源出处。

好的 谢谢建议 我更新下简介。可能当初主要想的是跟做项目，基本上都是把讲义里的代码敲一遍，记录下来，所以整理的部分比较少
